export const LOGIN_USER_SUCCEED = 'LOGIN_USER_SUCCEED';
export const LOGIN_USER_FROM_STORAGE_SUCCEED = 'LOGIN_USER_FROM_STORAGE_SUCCEED';
export const LOGOUT_USER_SUCCEED = 'LOGOUT_USER_SUCCEED';
export const GET_MY_USER_INFO_SUCCEED = 'GET_MY_USER_INFO_SUCCEED';
