export const LOGIN_USER_SUCCEED = 'LOGIN_USER_SUCCEED';
export const LOGIN_USER_FROM_STORAGE_SUCCEED = 'LOGIN_USER_FROM_STORAGE_SUCCEED';
export const LOGOUT_USER_SUCCEED = 'LOGOUT_USER_SUCCEED';
export const GET_MY_USER_INFO_SUCCEED = 'GET_MY_USER_INFO_SUCCEED';

export const GET_FIRST_UNANSWERED_QUESTIONS_SUCCEED = 'GET_FIRST_UNANSWERED_QUESTIONS_SUCCEED';
export const GET_FIRST_UNANSWERED_QUESTIONS_FAIL = 'GET_FIRST_UNANSWERED_QUESTIONS_FAIL';

export const GET_MORE_UNANSWERED_QUESTIONS_SUCCEED = 'GET_MORE_UNANSWERED_QUESTIONS_SUCCEED';
export const GET_MORE_UNANSWERED_QUESTIONS_FAIL = 'GET_MORE_UNANSWERED_QUESTIONS_FAIL';

export const GET_FIRST_ANSWERED_QUESTIONS_SUCCEED = 'GET_FIRST_ANSWERED_QUESTIONS_SUCCEED';
export const GET_FIRST_ANSWERED_QUESTIONS_FAIL = 'GET_FIRST_ANSWERED_QUESTIONS_FAIL';

export const GET_MORE_ANSWERED_QUESTIONS_SUCCEED = 'GET_MORE_ANSWERED_QUESTIONS_SUCCEED';
export const GET_MORE_ANSWERED_QUESTIONS_FAIL = 'GET_MORE_ANSWERED_QUESTIONS_FAIL';

export const GET_FIRST_FOLLOWING_LIST_SUCCEED = 'GET_FIRST_FOLLOWING_LIST_SUCCEED';
export const GET_FIRST_FOLLOWING_LIST_FAILED = 'GET_FIRST_FOLLOWING_LIST_FAILED';

export const GET_MORE_FOLLOWING_LIST_SUCCEED = 'GET_MORE_FOLLOWING_LIST_SUCCEED';
export const GET_MORE_FOLLOWING_LIST_FAILED = 'GET_MORE_FOLLOWING_LIST_FAILED';

export const FOLLOW_OR_UNFOLLOW_USER_SUCCEED = 'FOLLOW_OR_UNFOLLOW_USER_SUCCEED';
